OHIF/react-vtkjs-viewport

- example/package.json
If my commit message is off, I'm sorry. I had to disable husky to commit. The current setup is unable to find `node` when running hooks.
> chore(scripts): cross platform support for copy

- .npmrc
- examples/VTKCornerstonePaintingSyncExample.js
- src/VTKViewport/createLabelPipeline.js
Refactor of: #26 after repo changes.
Sister to : cornerstonejs/react-cornerstone-viewport#39
Upgrade the example to use cornerstoneTools 4.0. Upgrade and fix the sync example.
> feat: 🎸 CorerstoneTools 4.0 + vtk-js brush sync example

- examples/VTKCornerstonePaintingSyncExample.js
- package.json
- src/Custom/VTKMPRViewport.js
- src/VTKViewport/View2D.js
- src/VTKViewport/View3D.js
- yarn.lock
Long overdue update since https://github.com/Kitware/vtk-js/pull/1211. Improves performance of synced brush usage.
> Brush stroke performance

- examples/App.js
- examples/VTKCornerstonePaintingSyncExample.js
- examples/VTKLoadImageDataExample.js
- examples/VTKMPRRotateExample.js
- package.json
- src/Custom/VTKMPRViewport.js
- src/VTKViewport/View2D.js
- src/VTKViewport/View3D.js
- src/lib/getImageData.js
- src/lib/loadImageData.js
- yarn.lock
Use a Float32Array and fill it using the cornerstone Int16 data to avoid recalculation. Also prevent multiple loadImageData calls on the same imageDataObject from overloading each other.
~3-3.5 faster on large CTs when tested in OHIF Viewer.
> perf: ⚡️ Use Float32Array and avoid duplicated slice insertion

- examples/VTKBasicExample.js
- examples/VTKCornerstonePaintingSyncExample.js
- examples/VTKCrosshairsExample.js
- examples/VTKMPRPaintingExample.js
- examples/VTKMPRRotateExample.js
- src/VTKViewport/View2D.js
- src/VTKViewport/vtkInteractorStyleMPRCrosshairs.js
Make the platform more Developer friendly and extensible:
- Makes swapping/instatiation of tools cleaner.
- Manager istyle callbacks within the component, allow synchronisation by passing in callbacks when setting a tool through the API.
- Updated all examples.
- Moved as much logic from OHIF/Viewers down to the component as possible.
The paint widget in `View2D`, and the `View3D` component are currently untouched.
> refactor: 💡 Refactor API and View2D usage

- examples/App.js
- examples/VTKFusionExample.js
- examples/VTKVolumeRenderingExample.js
- src/lib/getImageData.js
Fixes a bug we actually fixed as a side affect of switching to correctly using modality pixel values, by removing the erroneous attempt to fix it beforehand.
> Volume rendering fix

- src/lib/getImageData.js
The cross method from cornerstone-math modifies the calling object. Update code to correctly use this function.
> Fix cross product to compute Z direction in getImageData

- examples/VTKCrosshairsExample.js
- package.json
- src/VTKViewport/View2D.js
- src/lib/getImageData.js
- yarn.lock
Fix a property which was removed at some point.
> fix: 🐛 Added back imageMetaData0 which was removed

- examples/VTKCrosshairsExample.js
- package.json
- yarn.lock
> fix: 🐛 Fix Parallel Projection with new vtk.js version

- src/VTKViewport/View2D.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/lib/data/insertSlice.js
- src/lib/getImageData.js
- src/lib/loadImageData.js
Switch to orienting the volume actor differently depending on its
acquisition direction, rather than filling up the volume differently.
> fix: 🐛 Switch to orienting the volume actor differently

- package.json
- postcss.config.js
Development changes:
- Run `yarn link` in `react-vtkjs-viewport` project root
- Run `yarn link react-vtkjs-viewport` in monorepo root
WebPack will now watch `react-vtkjs-viewport` for changes and rebuild/reload when detected.
The "module" key tells WebPack to use `react-vtkjs-viewport`'s `src/index.js` as the entry point (if it is available). Because our PWA build is compatible with `react-vtkjs-viewport`, everything works seamlessly :+1:
For individuals importing `react-vtkjs-viewport` without a link, they will continue to use the "main" key's entrypoint (`dist/index.umd.js`), as we don't publish the source when shipping to NPM (this is good, as we don't have an ESM target for `module`)
> chore: support monorepo PWA linking w/ yarn link

- examples/VTKCornerstonePaintingSyncExample.js
- examples/VTKFusionExample.js
- examples/VTKMPRPaintingExample.js
- package.json
- src/VTKViewport/View2D.js
- src/VTKViewport/View3D.js
- src/VTKViewport/createLabelPipeline.js
- src/lib/getImageData.js
- yarn.lock
Update `vtk.js` peer dependency to `11.14.0` to pull in this change: https://github.com/Kitware/vtk-js/pull/1264
outline rendering is on by default for View2D, but can be turned off by passing in a custom`labelmapRenderingOptions` prop. This object now has the property `renderOutline` which true by default. You can also set the thickness of the rendered outline using the `outlineThickness` property of `labelmapRenderingOptions`. This defaults to 3 if unset.
> feat: 🎸 Enable outline rendering of segmentations

- examples/VTKCrosshairsExample.js
- src/VTKViewport/View2D.js
- src/VTKViewport/View3D.js
- src/VTKViewport/vtkInteractorStyleMPRCrosshairs.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/VTKViewport/vtkSVGCrosshairsWidget.js
This PR makes scroll/pan/zoom update the crosshairs correctly when using either `vtkInteractorStyleMPRSlice` or `vtkInteractorStyleMPRCrosshairs`.
Updates for `vtkInteractorStyleMPRRotate` will come in the future or during a large refactor of the iStyle framework we have in place.
> Fix Crosshair Update on scroll/pan/zoom.

- src/VTKViewport/View2D.js
- src/VTKViewport/createLabelPipeline.js
This PR adds easy api methods to change the individual segment LUTs of the labelmap of the View2D component.
`api.setSegmentRGBA(segmentIndex, [red, green, blue, alpha])`
`api.setSegmentRGB(segmentIndex, [red, green, blue])`
`api.setSegmentAlpha(segmentIndex, alpha)`
I also added a helper that mirrors Cornerstone's `cornerstone.updateImage(enabledElement)` function for forcing a re-render, as it ends up being used a lot:
`api.updateImage()`
TODO: Checked it works in console, but a demo for this would be nice.
> Color LUT api

- src/VTKViewport/View2D.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/helpers/index.js
- src/helpers/uuidv4.js
Per our conversation yesterday, I need a way to know when and which a VTK Viewport is scrolled. It appears the default event is blocked/prevented by VTK internally. This attempts to re-emit the event as a `vtkscrollevent` so I can consume it somewhere else.
The addition of a `uid` on the "api" object, and on the `interactorStyle` are to provide a way for me to determine, for a given `viewportIndex`, if it was the event's emitter.
Related: https://github.com/OHIF/Viewers/pull/1139
> feat: dispatch vtk scroll event

- src/VTKViewport/View2D.js
- src/VTKViewport/createLabelPipeline.js
The colorLUTApi recently introduced erroneously used addPoint rather than addPoint long, thus the last two parameters (midpoint and sharpness) weren't being passed to the vtkjs class. This meant they defaulted to linear and caused problems that would cause hidden segments to display sometimes.
> fix: 🐛 addPoint to addPointLong so that we have a constant ofun

- examples/VTKCornerstonePaintingSyncExample.js
- examples/VTKMPRPaintingExample.js
- package.json
- src/VTKViewport/View2D.js
- yarn.lock
Update examples to use Float32Arrays for segmentations, as well as use a
new cornerstoneTools release for the cornerstone-sync example.
> fix: 🐛 Update examples to use Float32Arrays for segmentations

- src/VTKViewport/vtkInteractorStyleMPRSlice.js
Prevents the onScroll callback from trying to reset crosshairs when they haven't been initialised yet.
> fix: 🐛 Fix onScroll throwing when crosshairs arent initialised

- src/VTKViewport/View3D.js
We need to tell vtkjs to release the memory when our component is no longer in use.
Otherwise renderer context will stay and after a while it will crash the browser.
> fix: 🐛 Memory leak in View3D

- src/VTKViewport/View2D.js
We need to tell vtkjs to release the memory when our component is no longer in use.
Otherwise renderer context will stay and after a while it will crash the browser.
> fix: 🐛 Memory leak in View2D

- examples/VTKCornerstonePaintingSyncExample.js
- examples/VTKCrosshairsExample.js
- examples/VTKFusionExample.js
- examples/VTKLoadImageDataExample.js
- examples/VTKVolumeRenderingExample.js
- package.json
- src/lib/getImageData.js
- src/lib/loadImageData.js
Switched to using the `cornerstone-tools` requestPoolManager, so that we don't send 1000 requests at the same time to the PACS on `imageDataObject.loadImage()`.
This is a breaking change, as we the imageDataObject no-longer has insertPixelDataPromises, instead the consumer may subscribe to an imageDataObject's onPixelDataInserted and/or onAllPixelDataInserted hooks. All the relavent  examples have been updated to reflect this. As we are still pre-1.0, I have avoided a major version bump.
> [OHIF/Viewers: IDC-1957] Switch to using request pool manager.

- src/lib/getImageData.js
- src/lib/loadImageData.js
Add `onPixelDataInsertedError` handler to `imageDataObject`s.
Progressive loading will no longer hang if one or more lines fails, and a `onAllPixelDataInserted` will be published when all requests are complete, regardless if they are successful or not. This allows you to at least view volumes that may have one missing slice.
> fix: 🐛 Handle failed loads when fetching data

- examples/App.js
- examples/VTKRotatableCrosshairsExample.js
- src/VTKViewport/View2D.js
- src/VTKViewport/vtkInteractorStyleMPRRotate.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
- src/VTKViewport/vtkSVGCrosshairsWidget.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget copy.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget.js
- src/ViewportOverlay/ViewportOverlay.js
- src/helpers/liangBarksyClip.js
- src/index.js
This PR adds rotatable crosshairs.
This adds a rotatable crosshair implementation with handles for rotation and draggable lines. You can optionally choose whether to show the angles relative to the original orientation for each viewport.
This does not remove the old crosshair implementation as many are dependent on it.
[Demo link](https://deploy-preview-115--react-vtkjs-viewport.netlify.app/rotatable-crosshairs)
> Rotatable crosshairs

- examples/VTKRotatableCrosshairsExample.js
- src/VTKViewport/View2D.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget.js
This fixes:
- Pan.
- Adds an api to reset the orientation/crosshairs + added that to the demo.
- Placement of the color reference indicator for non-square viewports.
This adds:
- Adds the ability to select a reference line then use the mouse wheel to scroll it.
- Adds the option to disable normal scroll when crosshairs are on (default off).
> Rotatable crosshairs updates

- examples/VTKRotatableCrosshairsExample.js
- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget.js
- The reference lines where inverted with respect to the canvas, due to not accounting for a switch from displayCoordinates to SVG, causing a clockwise rotation to map to an anti-clockwise rotation.
- Fixed this issue.
- Changed the rotatable crosshairs example to use a head scan, which makes it much easier to identify such issues.
> fix: 🐛 SVG orientation fix

- examples/VTKRotatableCrosshairsExample.js
- src/VTKViewport/vtkInteractorStyleMPRSlice.js
- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
Fix various issues related to scroll/pan/zoom interaction with the rotatable crosshairs.
> fix: 🐛 Fix scroll issues with rotatable crosshairs

- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget.js
- Crosshairs thinner
- Rotate handle smaller
- Rotate handle only appears on mouse over of the line/handle, or during rotation.
- You can no longer scroll the crosshairs offscreen.
> fix: 🐛 Make crosshair handle thickness configurable. fix bug

- src/VTKViewport/vtkInteractorStyleRotatableMPRCrosshairs.js
- src/VTKViewport/vtkSVGRotatableCrosshairsWidget.js
make crosshair linked views rotations around the focus of the crosshair
fix focal points position after rotations and pannings of the crosshair.
> fix: 🐛 #2127

- examples/VTKCrosshairsExample.js
- examples/VTKFusionExample.js
- examples/VTKMPRRotateExample.js
- examples/VTKRotatableCrosshairsExample.js
- examples/VTKVolumeRenderingExample.js
Demos were broken since they were using old dcmjs server studies
a broken demo: https://react-vtkjs-viewport.netlify.app/volume-rendering
> fix: various demos that were using old dcmjs study uids
